# Generated by Django 4.1.7 on 2023-03-19 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('p', 'programming'), ('i', 'interests'), ('l', 'life')], max_length=1),
        ),
    ]
