# Generated by Django 4.1.7 on 2023-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_blog_photo_alter_course_certificate_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='blocks',
            field=models.TextField(default='Python'),
            preserve_default=False,
        ),
    ]
