# Generated by Django 4.1.7 on 2023-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_education_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='blocks',
            field=models.TextField(blank=True),
        ),
    ]
