# Generated by Django 4.1.7 on 2023-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_alter_education_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='aaa', max_length=30),
            preserve_default=False,
        ),
    ]
