# Generated by Django 4.1.7 on 2023-03-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_experience_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
