# Generated by Django 4.1.7 on 2023-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0006_alter_experience_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
