# Generated by Django 4.1.7 on 2023-03-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0009_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
