# Generated by Django 4.1.7 on 2023-03-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0010_remove_course_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-pk'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
