# Generated by Django 4.1.7 on 2023-03-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0012_alter_book_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='blocks',
            new_name='competences',
        ),
    ]
