# Generated by Django 4.1.7 on 2023-03-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0013_rename_blocks_education_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.AddField(
            model_name='course',
            name='competences',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
