# Generated by Django 4.1.7 on 2023-03-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0014_remove_course_certificate_course_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='recomendation',
        ),
        migrations.AddField(
            model_name='book',
            name='competences',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
