# Generated by Django 4.1.7 on 2023-03-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0016_alter_education_options_experience_competences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-end_date'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
